/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminCanteenOpsRouteImport } from './routes/admin.canteen-ops'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/admin/stock',
  path: '/admin/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCanteenOpsRoute = AdminCanteenOpsRouteImport.update({
  id: '/admin/canteen-ops',
  path: '/admin/canteen-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen-ops': typeof AdminCanteenOpsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen-ops': typeof AdminCanteenOpsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen-ops': typeof AdminCanteenOpsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/menu'
    | '/orders'
    | '/admin/analytics'
    | '/admin/canteen-ops'
    | '/admin/sales'
    | '/admin/stock'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/menu'
    | '/orders'
    | '/admin/analytics'
    | '/admin/canteen-ops'
    | '/admin/sales'
    | '/admin/stock'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/menu'
    | '/orders'
    | '/admin/analytics'
    | '/admin/canteen-ops'
    | '/admin/sales'
    | '/admin/stock'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCanteenOpsRoute: typeof AdminCanteenOpsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/admin/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/canteen-ops': {
      id: '/admin/canteen-ops'
      path: '/admin/canteen-ops'
      fullPath: '/admin/canteen-ops'
      preLoaderRoute: typeof AdminCanteenOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCanteenOpsRoute: AdminCanteenOpsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
